Repository docker/docker-py, pull requests merged in 2022-08, with the labels that each got.

#2929 Add `gzip` documentation to `BuildApiMixin`
  docker/api/build.py
Labels: group/documentation

#3019 docs: add changelog for 6.0.0
  docs/change-log.md
  tests/Dockerfile
Labels: group/documentation

#3029 Add sysctl support for docker swarm services
  docker/models/services.py
  docker/types/services.py
  tests/integration/api_service_test.py
  tests/unit/models_services_test.py
Labels: kind/enhancement

#2987 Add swarm support for DataPathPort
  docker/api/swarm.py
  docker/models/swarm.py
  tests/integration/api_swarm_test.py
Labels: dco/no

#3032 docs: install package in ReadTheDocs build
  .readthedocs.yml
Labels: group/documentation

#3031 feat: add support for floats to docker logs params since / until sinc…
  docker/api/container.py
  docker/models/containers.py
  tests/unit/api_container_test.py
Labels: kind/enhancement, level/dockerclient, level/apiclient
