Repository docker/docker-py, pull requests merged in 2022-07, with the labels that each got.

#3004 deps: upgrade pywin32 & relax version constraint
  requirements.txt
  setup.py
Labels: group/windows, dependencies

#3005 ci: remove Python 3.6 and add 3.11 pre-releases
  .github/workflows/ci.yml
Labels: release-management

#3006 utils: fix IPv6 address w/ port parsing
  docker/utils/utils.py
  tests/unit/utils_test.py
Labels: kind/bug, level/dockerclient

#3007 tls: use auto-negotiated highest version
  docker/tls.py
Labels: level/dockerclient

#3010 deps: test on Python 3.10 by default
  .readthedocs.yml
  Dockerfile
  Dockerfile-docs
  Jenkinsfile
  Makefile
  docs-requirements.txt
  docs/_static/custom.css
  setup.py
  tests/Dockerfile
  tests/Dockerfile-dind-certs
  tests/Dockerfile-ssh-dind
Labels: release-management, dependencies

#3011 deps: remove backports.ssl_match_hostname
  docker/transport/ssladapter.py
  requirements.txt
  tests/unit/ssladapter_test.py
Labels: dependencies

#3013 ci: bump version to 6.0.0-dev
  docker/version.py
Labels: release-management

#3014 deps: upgrade & remove unnecessary dependencies
  README.md
  appveyor.yml
  requirements.txt
  setup.py
  test-requirements.txt
Labels: dependencies

#3020 docs: fix markdown rendering
  docs-requirements.txt
  docs/conf.py
Labels: group/documentation

#3023 api: preserve cause when re-raising error
  docker/errors.py
Labels: level/apiclient

#3022 deps: upgrade websocket-client to latest
  requirements.txt
  tests/integration/api_container_test.py
Labels: dependencies

#2927 Add platform parameter for create_container()
  docker/api/container.py
  docker/errors.py
  docker/models/containers.py
  tests/unit/api_container_test.py
  tests/unit/models_containers_test.py
Labels: kind/enhancement, level/dockerclient, level/apiclient

#2930 Support cgroupns option in containers.run/containers.create
  docker/models/containers.py
  docker/types/containers.py
  tests/unit/models_containers_test.py
Labels: kind/enhancement, level/dockerclient, level/apiclient

#3026 model: add remove() to Image
  docker/models/images.py
  tests/unit/models_images_test.py
Labels: kind/enhancement, level/dockerclient

#2574 Fix TLS server check example to actually verify
  docs/tls.rst
Labels: group/documentation

#2573 Clarify TLSConfig verify parameter docs
  docker/tls.py
Labels: group/documentation

#3027 docs: fix RollbackConfig/Order values
  docker/types/services.py
Labels: group/documentation

#3018 ci: add workflow for releases
  .editorconfig
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .gitignore
  Dockerfile
  docker/__init__.py
  docker/constants.py
  docker/version.py
  docs/conf.py
  pyproject.toml
  setup.py
  tests/Dockerfile
Labels: release-management
