Repository docker/docker-py, pull requests merged in 2023-11, with the labels that each got.

#3123 feat: move websocket-client to extra dependency
  docker/api/client.py
  setup.py
Labels: kind/enhancement, dependencies

#3185 breaking: Python 3.12 compatibility & remove custom SSL adapter
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Dockerfile
  Dockerfile-docs
  Jenkinsfile
  docker/api/client.py
  docker/client.py
  docker/tls.py
  docker/transport/__init__.py
  docker/transport/ssladapter.py
  docker/utils/utils.py
  setup.py
  test-requirements.txt
  tests/Dockerfile
  tests/Dockerfile-dind-certs
  tests/unit/models_networks_test.py
  tests/unit/ssladapter_test.py
  tests/unit/utils_test.py
  tox.ini
Labels: breaking-change

#3188 chore: update MAINTAINERS and remove CODEOWNERS
  .github/CODEOWNERS
  MAINTAINERS
Labels: group/documentation
