Repository docker/docker-py, pull requests merged in 2024-01, with the labels that each got.

#3200 fix: keyerror when creating new config(#3110)
  docker/models/configs.py
  tests/unit/fake_api.py
  tests/unit/fake_api_client.py
  tests/unit/models_configs_test.py
Labels: kind/bug

#3202 docs: change image.history() return type to list (#3076)
  docker/api/image.py
  docker/models/images.py
Labels: group/documentation

#3205 Drop `packaging` dependency
  docker/utils/utils.py
  setup.py
  tests/unit/utils_test.py
Labels: dependencies
